baseURL = 'http://akkaoualid.github.io'
languageCode = 'en-us'
title = 'Oualid AKKA'
themesDir = "themes"
theme = "hugo-winston-theme"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true

[params]
  google_analytics_id = ""

  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false

  addFrame = true
  addDot = true

  highlightColor = '#7b16ff'
